name: Source & Build Stage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install UV
        uses: astral-sh/setup-uv@v3

      - name: Install Dependencies
        run: uv sync

      - name: Build Backend
        env:
          SECRET_KEY: "dummy"
          STATIC_URL: "/static/"
        run: uv run python manage.py collectstatic --noinput
